### ISSUE TITLE
Need help in correct implementaion

### ISSUE THREAD

**Issue by jmandivarapu1** [rodrigoramosrs/react-fullscreen-element#1]
Hi,

Firstly I liked the package because it has the scroll option which is quite unique and most of the full-screen packages doesn't have it.

Here is my issue I tried implementing on my page but it didn't behave the way I expected,

I am trying to make a part of my screen in full-screen mode...

<img width="1279" alt="Screen Shot 2019-06-11 at 9 01 08 AM" src="https://user-images.githubusercontent.com/21245519/59274260-f5628b00-8c27-11e9-8dd0-3e51e2a85d98.png">

So, when I click on full screen but it is behaving like this,

<img width="1278" alt="Screen Shot 2019-06-11 at 9 06 15 AM" src="https://user-images.githubusercontent.com/21245519/59274393-43778e80-8c28-11e9-95d1-c0588035bade.png">

I tried using the other packages but I don't have scroll option there

Expected behavior
Full screen like this with scroll option

<img width="1279" alt="Screen Shot 2019-06-11 at 9 08 16 AM" src="https://user-images.githubusercontent.com/21245519/59274537-846fa300-8c28-11e9-8db5-f23648888a78.png">

Please let me know if it is possible...or any way I can achieve this.

Thank you in Advance,

**Comment by rodrigoramosrs** [comment]
The main problem here is z-index of others elements in your application.

I will create one property to set zindex when the element goes to fullscreen.

To avoid this problem,  try lower zindex of your left menu and your navbar below 800.

**Comment by jmandivarapu1** [comment]
I fixed using some css property like overflow:auto,height:100% and width:100% to my div.

Thank you for your reply
